### ISSUE TITLE
Handtere utanlandske nummer som er sperra frå vår Twilio

### ISSUE THREAD

**Issue by madsop** [Roedt/ringesentralen-frontend#110]
Sia vi eksplisitt måtte opne for norske nummer, vil sikkert det samme dukke opp for svenske/danske/whatever numre også.

Trur ikkje vi treng å støtte det, men fint om vi kan gi ei ordenlteg melding om at brukaren må ringe manuelt, feks.

**Comment by zrrrzzt** [comment]
Skal vi støtte det? Da må i så fall en del annen logikk også skrives om mtp hvordan f.eks. mobilnummer automatisk får norsk landskode i front.

Dersom vi alltid stoler på det som er lagt inn i databasen vil jeg heller foreslå at Twilio bare åpnes for de landene vi har tenkt og ikke gjør noe mer hverken i front eller back.

**Comment by madsop** [comment]
I prod-Hypersys er det mange forskjellige landkodar det går an å setje. Litt usikker på formatet på veljar-listene. Uansett tenkjer eg vi ikkje treng å støtte _IP-ringing dit_, men at applikasjonen bør gi ei fin feilmelding ("Nils Nilsen har eit utanlandsk nummer. Vi støtter ikkje ringing til det frå systemet per no, så vil du ringe Nils Nilsen må du plukke opp telefonen og ringe manuelt") eller iallfall ikkje tryne.

**Comment by zrrrzzt** [comment]
Må få en liste over land vi har tenkt å støtte da @KristofferLer 
Antar Sverige og Danmark er nærliggende i tillegg til Norge?
Evt kan du gjøre det enkelt for oss @madsop : Er det nummer på medlemslistene i det hele tatt som er utenfor Norge :-)

**Comment by KristofferLer** [comment]
Hei. Tenker det holder fint med Norge

Med vennlig hilsen
Kristoffer Lia Lerstang
Organisasjonssekretær

Tlf: 22 98 90 72
Mobil: 975 73 278
rødt.no

--- original message ---
On 31 March 2021, 6:48 AM CEST ***@***.*** wrote:



Må få en liste over land vi har tenkt å støtte da @KristofferLer

Antar Sverige og Danmark er nærliggende i tillegg til Norge?

Evt kan du gjøre det enkelt for oss @madsop : Er det nummer på medlemslistene i det hele tatt som er utenfor Norge :-)

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by zrrrzzt** [comment]
<img width="1194" alt="Screenshot 2021-04-01 at 07 14 47" src="https://user-images.githubusercontent.com/2197936/113246817-0fb49f80-92ba-11eb-911c-ec66cf03366e.png">

Da viser jeg nå en slik en for andre landkoder en Norge i stedet for "Bruk VoIP" knappen.
